### ISSUE TITLE
[BUG] Issue with large chunk_size

### ISSUE THREAD

**Issue by cheungdaven** [autogluon/autogluon-rag#50]
If the chunk_size is longer than 2048, there are some unexpected behaviors especially using bedrock embeddings models.

> botocore.errorfactory.ValidationException: An error occurred (ValidationException) when calling the InvokeModel operation: Malformed input request: #/texts/1: expected maxLength: 2048, actual: 2449#/texts/2: expected maxLength: 2048, actual: 2227#/texts/4: expected maxLength: 2048, actual: 3072#/texts/11: expected maxLength: 2048, actual: 2777#/texts/12: expected maxLength: 2048, actual: 2949#/texts/15: expected maxLength: 2048, actual: 2053#/texts/17: expected maxLength: 2048, actual: 2769#/texts/18: expected maxLength: 2048, actual: 2399#/texts/19: expected maxLength: 2048, actual: 2403, please reformat your input and try again.

A more user friendly setting is to allow text longer than 2048 as it can be handled by many LLMs during generation, but sacrifice the embedding performance by truncating the text_chunk to 2048.

**Comment by shreyash2106** [comment]
Thanks for submitting this issue Shuai! 

I will create a PR to address this issue with bedrock models.

**Comment by shreyash2106** [comment]
Fix in #53
