### ISSUE TITLE
[BUG] The meta_data has repeated {doc_id, chunk_id}

### ISSUE THREAD

**Issue by cheungdaven** [autogluon/autogluon-rag#51]
The metadata will sometimes generate 
{"doc_id":3,"chunk_id":0,"text":"text 1"}
{"doc_id":3,"chunk_id":0,"text":"text 2"}

To reproduce:
If you have 30 documents in the directory but set pipeline_batch_size to a number smaller than 30. This repetition will happen.

**Comment by shreyash2106** [comment]
Thanks for submitting this Shuai!

The reproduction tip is very helpful as the bug makes sense in that context. I will create a PR to fix this

**Comment by shreyash2106** [comment]
PR to fix this: #52
